name: baahiTire_app
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  url_launcher: ^6.3.1
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  cached_network_image: ^3.4.0
  sqflite: ^2.3.3+1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/baahi.png"
